
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          progress() {
            while [ 0 ]
              do
                echo "tick"
              done
          }
          progress &
          sleep 20
          
