
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          progress() {
            pc=0;
            while [ 0 ]
              do
                echo "$pc sec"
                sleep 1
                ((pc++))
              done
          }
          progress &
          sleep 10
          
